### ISSUE TITLE
Sockets, SSLSocket, and run_forever()

### ISSUE THREAD

**Issue by sotte** [capnproto/pycapnp#105]
One can pass sockets into the `TwoPartyServer` and `TwoPartyClient`. The documentation makes it sound like it should be possible to use encrypted transports such as python's `SSLSocket`.

The Server looks something like this

```
_socket = socket.socket()
_socket.bind(("", 8888))
ssl_socket = ssl.wrap_socket(_socket, certfile="ssl_cert", keyfile="ssl_key")

server = capnp.TwoPartyServer(ssl_socket, bootstrap=CounterServer())
# server.run_forever()  # does not work when you pass a socket
```

The client looks something like this:

```
_socket = socket.socket()
ssl_socket = ssl.wrap_socket(_socket)
ssl_socket.settimeout(10)
ssl_socket.connect(("localhost", 8888))

client = capnp.TwoPartyClient(ssl_socket)
counter = client.bootstrap()
counter = counter.cast_as(counter_capnp.Counter)
print(counter.incr().wait())
```

So my question is: am I doing the right thing? How do I handle `server.run_forever()` when I pass (ssl-)sockets?

The note `In that case, run_forever will not work, and you will have to use on_disconnect.wait()` in the docs is not really helping.

**Comment by Cheaterman** [comment]
I'm having issues using sockets as well. For your server I feel like you're missing a `_socket.listen(1024)` statement or something similar, but I can't get sockets to work in general here. Also the doc is indeed not very helpful as `on_disconnect` is in fact a function returning a Promise, and should be used as server.on_disconnect().wait() - which returns immediately in my case.

**Comment by smasher816** [comment]
I can get sockets working by using an accept loop and creating a TwoPartyServer on each individual  connection (similar to this example. https://markusholtermann.eu/2016/09/ssl-all-the-things-in-python/)

```
client, addr = sock.accept()
server = capnp.TwoPartyServer( conn, bootstrap=<...>)
server.on_disconnect().wait()
```

Unfortunately when using an ssl wrapped socket I get a "Message has too many segments." error. Non-Encrypted sockets seem to work fine though

**Comment by Wiezzel** [comment]
@smasher816 
The way `TwoPartyClient` and `TwoPartyServer` are implemented makes it impossible to use SSL-encrypted sockets. Cap'n Proto server just takes `fileno()` from the supplied socket so the SSL layer is completely ignored:

https://github.com/capnproto/pycapnp/blob/29e63de41d9f0598437487863edf6ccb1f5e840a/capnp/lib/capnp.pyx#L2266
https://github.com/capnproto/pycapnp/blob/29e63de41d9f0598437487863edf6ccb1f5e840a/capnp/lib/capnp.pyx#L2371

**Comment by Cheaterman** [comment]
Glad you brought this up - for similar reasons, it's not (yet?) possible to
do UDP in there, because the server expects to write to an accepted socket
(which has an implicit target address). There's most likely other issues
inside Capnp itself that would need to be addressed for either UDP or
SSLSockets, I suppose.

Le ven. 15 mars 2019 à 14:32, Adam Wierzbicki <notifications@github.com> a
écrit :

**Comment by haata** [comment]
@Wiezzel I have gotten a Python to Python example using SSL to work here https://github.com/haata/pycapnp/tree/asyncio_ssl

I'm going to try Python Client to Rust Server next.

**Comment by haata** [comment]
This is now working on `master`.

See
- https://github.com/capnproto/pycapnp/blob/master/examples/async_ssl_client.py
- https://github.com/capnproto/pycapnp/blob/master/examples/async_ssl_server.py
