### ISSUE TITLE
Unable to build bdist_wheel on Ubuntu 14.04

### ISSUE THREAD

**Issue by vitaly-krugl** [capnproto/pycapnp#109]
I tried building from source on Ubuntu 14.04, following instructions in README, but am getting all sorts of failures.

```
$ python -m platform
Linux-4.2.0-27-generic-x86_64-with-Ubuntu-14.04-trusty

$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

$ python --version
Python 2.7.6

$ pip --version
pip 8.1.2 from /home/vitaly/.local/lib/python2.7/site-packages (python 2.7)

>>> import setuptools
>>> setuptools.__version__
'25.1.1'
>>> import distutils
>>> distutils.__version__
'2.7.6'
```

NOTE the warning about `entry_points` and `install_requires` as well as "error: invalid command 'bdist_wheel'" below:

```
$ python setup.py bdist_wheel --disable-cython
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

**Comment by jparyani** [comment]
Sorry, I'm not familiar at all with building wheels. If anyone has any input, I'd be happy to accept a PR.

**Comment by vitaly-krugl** [comment]
It appears that all binary distribution build types are failing, including bdist_dumb. If followed [instructions for building bdist_dumb in pycapnp/README.md](https://github.com/jparyani/pycapnp/blob/5d69eda752b54ceeb06819fac3dc5f7b692c8d4e/README.md), but ended up with the following failure. This result is from centos-6.8 with python 2.7.11. I recall getting an identical failure on Ubuntu-14.04 as well. 

```
# python setup.py bdist_dumb --disable-cython
/opt/python/cp27-cp27mu/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/opt/python/cp27-cp27mu/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --disable-cython not recognized
```

**Comment by jparyani** [comment]
Try replacing line#6 in setup.py with `from setuptools import setup` (https://github.com/jparyani/pycapnp/blob/d85200cee34653b6df8b2c8484a6f541f66a8ddd/setup.py#L6). Also make sure to `pip install wheel` first.

I'll test it out some more and make sure this is a safe change to make. I vaguely remember there being some incompatibilities between different cython and setuptools versions back in the day, but maybe it's better now especially considering most users will never use cython anyways.

**Comment by vitaly-krugl** [comment]
@jparyani, I saw the `setuptools` recommendation in issue #88 and tried it, but it didn't help. `wheel` was installed, too.

**Comment by vitaly-krugl** [comment]
Failure with `from setuptools import setup` on Ubuntu 14.04 and tool versions described in the original issue description:

```
p$ python setup.py bdist_dumb --disable-cython
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --disable-cython not recognized
```

**Comment by scottpurdy** [comment]
Looks like the wheel section of the README was added by @rhyolight so maybe he has some thoughts.

**Comment by jparyani** [comment]
I'm not sure what changed under the hood, but bdist_wheel seems to not work with command line params. You can get around this by explicitly cythonizing the files first and then doing bdist_wheel:
```
python setup.py build --force-cython
python setup.py bdist_wheel 
```

**Comment by rhyolight** [comment]
@vitaly-krugl Try an updated version of `setuptools`?

    pip install -U setuptools

**Comment by haata** [comment]
This should be working now. It is recommended to use pipenv when running the build locally on your machine.
