### ISSUE TITLE
Handle file-like objects without a "fileno"

### ISSUE THREAD

**Issue by scottpurdy** [capnproto/pycapnp#142]
I was trying to use `StringIO` in a test to avoid dealing with file clean up and got this error attempting to write a pycapnp message to the `StringIO` instance:

```
AttributeError: StringIO instance has no attribute 'fileno'
```

Is it possible to support this scenario?

**Comment by haata** [comment]
This has more to do with how capnproto handles the socket file.
I'd recommend you use the recent asyncio additions.

Unless I'm misunderstanding the use case.

**Comment by 0x00-pl** [comment]
what is 'the recent asyncio additions' ?

**Comment by haata** [comment]
See https://capnproto.github.io/pycapnp/quickstart.html#starting-a-client-asyncio
