### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by ofek** [capnproto/pycapnp#147]
@jparyani As of 0.6 Windows is fully supported https://capnproto.org/news/2017-05-01-capnproto-0.6-msvc-json-http-more.html

pycapnp should now provide binary wheels for Windows, probably via the Appveyer ci service.

**Comment by diorcety** [comment]
Please check my branch https://github.com/diorcety/pycapnp/tree/msvc with the capnp branch https://github.com/diorcety/capnproto/commits/dll (from https://github.com/sandstorm-io/capnproto/issues/480)
I succesfully compiled capnp & pycapnp on Windows with dll

**Comment by tarehart** [comment]
I would really appreciate windows support. Please take up @diorcety on his offer if he's kind enough to honor it a year later.

**Comment by haata** [comment]
Windows is now supported on `master`! I will be pushing Pypi packages once a few more issues are fixed.
