### ISSUE TITLE
capnp 0.6.0 support

### ISSUE THREAD

**Issue by zielmicha** [capnproto/pycapnp#151]
It seems  pycapnp can't be built with the new Cap'n Proto release 0.6.0:
```capnp/lib/capnp.cpp:35582:283: error: no matching function for call to ‘kj::Quantity<long int, kj::_::NanosecondLabel>::Quantity(int64_t&)’```

(#149 is probably related)

**Comment by vladpetric** [comment]
Is this project effectively abandonware?

**Comment by jparyani** [comment]
Unfortunately, I have had less time to work on pycapnp recently. I don't have any active personal projects that use pycapnp anymore, so I have been less motivated to actually work on it.

That being said, I'm happy to come through every month or so and merge PRs fixing issues and do a release to PyPi. Also long-term, if anyone stands out as a contributor and seems willing to take over, I and/or @kentonv would be happy to give them merge rights.

**Comment by vladpetric** [comment]
Understood.

Thank you for the recent commits and fixes!

Vlad

**Comment by chaoflow** [comment]
According to https://github.com/capnproto/pycapnp/commit/74618de3efab0dd44e12156c3613f751cb57aa7d Pycapnp is shipping 0.6.1. This issue can be closed

**Comment by dureuill** [comment]
I guess this issue could be repurposed to "capnp 0.7.0 support" now? 

When trying to import pycapnp with a capnproto library obtained from the archlinux packages (capnproto 0.7), I get an ImportError related to TransformPromiseNodeBaseonReadyEvent not being defined.

From `version.py`, I can tell that the target version of my pycapnproto install (donwloaded from pip) is 0.6.4.

Thank you for any answer.

**Comment by haata** [comment]
The master branch now requires at least capnp 0.7.0.

**Comment by MaxNoe** [comment]
@haata could you then issue a new release to pypi please?

**Comment by haata** [comment]
I'll try to push one out this weekend.
