### ISSUE TITLE
ModuleNotFoundError: No module named 'schema_capnp'

### ISSUE THREAD

**Issue by emembrives** [capnproto/pycapnp#168]
Hello,

I have been trying to install pycapnp on Linux/Debian testing using the instructions at http://capnproto.github.io/pycapnp/install.html, but failing with the error in the title. I have python3 (3.6.4-1), cython3 (0.26.1-0.4) and capnproto (0.6.1-1) installed:
```
sudo apt install python3 python3-dev cython3 capnproto
```
I installed pycapnp through pip (but I have the same results when I tried installing from source):
```
pip3 install pycapnp  
Collecting pycapnp
  Downloading pycapnp-0.6.3.tar.gz (455kB)
    100% |████████████████████████████████| 460kB 3.3MB/s 
Building wheels for collected packages: pycapnp
  Running setup.py bdist_wheel for pycapnp ... done
  Stored in directory: /home/etienne/.cache/pip/wheels/a1/3c/15/1842ef04ba7b766afa1fc7cc0458536bebacee6620cd4864bc
Successfully built pycapnp
Installing collected packages: pycapnp
Successfully installed pycapnp-0.6.3
```
I can compile a schema for c++ (`capnp compile proto.capnp -oc++`), but I get this error when trying to compile for python:
```
capnp compile proto.capnp -ocython
Traceback (most recent call last):
  File "/home/etienne/.local/bin/capnpc-cython", line 7, in <module>
    from capnp._gen import main
  File "/home/etienne/.local/lib/python3.6/site-packages/capnp/_gen.py", line 4, in <module>
    import schema_capnp
ModuleNotFoundError: No module named 'schema_capnp'
cython: plugin failed: exit code 1
```

Am I doing something wrong? Is there something else I need to install?

Thanks

**Comment by jparyani** [comment]
Sorry the “-ocython” option is unsupported. This probably deserves a better call out in the README, but all you have to do is call ‘import proto_capnp’. See http://jparyani.github.io/pycapnp/quickstart.html#load-a-cap-n-proto-schema for more docs on how this works.

**Comment by emembrives** [comment]
Thanks for the explanation!

**Comment by harlanwaldrop** [comment]
For others finding your way here. It looks like today you can simply import your schema directly, i.e., given `events.capnp` this code was sufficient for me:

```python
import capnp
import events_capnp
```
