### ISSUE TITLE
Error while importing capnp: Symbol not found: __ZNSt11logic_errorC2EPKc

### ISSUE THREAD

**Issue by nbro** [capnproto/pycapnp#172]
### System Information

> OS: Mac OS X: High Sierra, v. 10.13.6.
g++: g++ (GCC) 6.3.1 20170510 (for GNAT GPL 2017 20170515)
clang++: Apple LLVM version 9.1.0 (clang-902.0.39.2) (Target: x86_64-apple-darwin17.7.0)
Python: 2.7.15
Pycapnp: 0.6.3 

I installed capnp using brew (as mentioned [here](https://capnproto.org/install.html)). 

I open an interactive Python shell. I try to import `capnp` by issuing the command, and this is the output

```
Python 2.7.15 (default, Jun 17 2018, 12:46:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import capnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/capnp/__init__.py", line 34, in <module>
    from .version import version as __version__
  File "/usr/local/lib/python2.7/site-packages/capnp/version.py", line 4, in <module>
    from .lib.capnp import _CAPNP_VERSION_MAJOR as LIBCAPNP_VERSION_MAJOR
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/capnp/lib/capnp.so, 2): Symbol not found: __ZNSt11logic_errorC2EPKc
  Referenced from: /usr/local/lib/python2.7/site-packages/capnp/lib/capnp.so
  Expected in: /usr/lib/libstdc++.6.0.9.dylib
 in /usr/local/lib/python2.7/site-packages/capnp/lib/capnp.so
>>>
```

I get the same error even if I create a file containing that import statement and then execute the Python script using `python import_capnp.py`.

How can I solve this problem?

**Comment by haata** [comment]
This usually means versions of the capnproto got mixed during compilation of pycapnp.
The best thing to do is to do a clean build of pycapnp. If you've manually installed capnproto make sure it's up to date (0.7.0). If that's not possible, you'll want to force the bundled capnproto: https://github.com/capnproto/pycapnp/tree/master#building-and-installation
