### ISSUE TITLE
traversal_limit_in_words keyword arg does not work with TwoPartyServer

### ISSUE THREAD

**Issue by pdiffley** [capnproto/pycapnp#181]
There appears to be a test for setting the traversal limit for a TwoPartyClient in test/test_rpc.py, but there is no test for a TwoPartyServer. When I set the traversal_limit_in_words for a TwoPartyServer, the default limit seems to still be used. With the limit set to 1, all messages still went through, and with the limit set to sys.maxsize, a large message (but not larger than sys.maxsize) still caused an exception.

**Comment by cjermain** [comment]
Thanks for reporting this @pdiffley! Are you up for doing a PR?

**Comment by pdiffley** [comment]
I can’t right now but might be able to in the future. I mostly just wanted to mark it as a problem in case others were troubleshooting the same issue.
