### ISSUE TITLE
How to instantiate a generic struct

### ISSUE THREAD

**Issue by n1try** [capnproto/pycapnp#188]
Could somebody please help me with generic structs? I have code that looks as follows.

**Schema:**
```
struct Coordinate {
    lat @0 :Float32;
    lon @1 :Float32;
    alt @2 :Float32;
}

struct Relation(Subject) {
    confidence @0 :Float32;
    subject @1 :Subject;
}

struct Actor {
    position @0 :Relation(Coordinate);
}
```

**Script:**
```python
    a = schema.Actor.new_message()

    position = schema.Coordinate.new_message()
    position.lat = 49.472
    position.lon = -112.980

    position_relation = schema.Relation.new_message()
    position_relation.confidence = 0.98
    position_relation.subject = position

    a.position = position_relation
```

Apparently, generics don't work that way, since I'm getting an exception:

`capnp.lib.capnp.KjException: capnp/dynamic.c++:576: failed: expected structValue.getSchema() == structType; Value type mismatch.`

Any ideas? I'd appreciate it!

**Comment by haata** [comment]
See https://github.com/capnproto/pycapnp/issues/173#issuecomment-431640043
