### ISSUE TITLE
Add Jacob Alexander as maintainer of pycapnp?

### ISSUE THREAD

**Issue by kentonv** [capnproto/pycapnp#194]
@haata has done some great work cleaning up and modernizing pycapnp here: https://github.com/haata/pycapnp-async

I'd like to grant him commit rights to this repo so that he can upstream this stuff and help maintain the project going forward.

@cjermain and @jparyani, do you have any objections?

**Comment by cjermain** [comment]
@kentonv, that sounds great. I've been fairly inactive as an interim maintainer, and happy to pass the torch to @haata.

**Comment by kentonv** [comment]
@haata is now added as a maintainer.

**Comment by haata** [comment]
@cjermain Would you mind adding me to the pypi repo as a maintainer? (I'm not sure @kentonv has access to that).

https://pypi.org/project/pycapnp/
https://pypi.org/user/HaaTa/ <- Me

**Comment by kentonv** [comment]
Can you add me too while you're at it?

https://pypi.org/user/kentonv/

I don't plan to publish any packages, just would like to have access as a fallback.

**Comment by cjermain** [comment]
@haata and @kentonv, I don't have access to add you. @jparyani, can you add them?

**Comment by jparyani** [comment]
I've added kentonv as an owner, and HaaTa as a maintainer.

**Comment by kentonv** [comment]
@jparyani Thanks!
