### ISSUE TITLE
Synchronous examples don't work anymore?

### ISSUE THREAD

**Issue by Cheaterman** [capnproto/pycapnp#208]
Hello - everything in the title. It seems like calculator_client.py and calculator_server.py don't work anymore. You'll get something along those lines:
```
  File "capnp/lib/capnp.pyx", line 1935, in capnp.lib.capnp._RemotePromise.wait
capnp.lib.capnp.KjException: capnp/rpc.c++:2477: disconnected: Peer disconnected.
```
Apparently, directly using `capnp.wait_forever()` does work? I'm not sure why however, because they're functionally equivalent, other than the check on `port_promise`... I'll keep investigating.

Another thing - you closed my merge request to have one bootstrap object be instanced by user (https://github.com/capnproto/pycapnp/pull/169), but it doesn't look like you currently provide an alternative (in sync mode)? (you may want me to open another issue about this?)

At the very least, it would be really important to give some access to the client IP/port somewhere - it seems like one of the most idiomatic ways to do this is to instance one bootstrap object per client (I discussed this with Kenton back in the day, and IIRC he said that's what people do in C++ - one object per client, not a single shared instance as it is now in pycapnp).

Thanks in advance!

EDIT: This appears to be a Heisenbug. My initial theory that it had something to do with wait_forever vs run_forever seems wrong. I also appear to sometimes get this:
```
  File "capnp/lib/capnp.pyx", line 1936, in capnp.lib.capnp._RemotePromise.wait
capnp.lib.capnp.KjException: (remote):0: disconnected: remote exception: expected nestingLimit > 0; Message is too deeply-nested or contains cycles.  See capnp::ReaderOptions.
```

EDIT2: Definitely a Heisenbug. I recompiled, adding some prints for debugging in both functions, and it seemed like run_forever() became more reliable than wait_forever()... I have absolutely no idea what's going on, possibly something to do with position independent code? I had to add fPIC to capnp's cmakelists... Lemme remove that, and recompile pycapnp without fPIC.

EDIT3: Can't recompile without PIC/PIE, fails to link with:
```
    /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld : /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/crt1.o : in function « _start » :
    (.text+0x20) : undefined reference to « main »
```
Further tests do seem to confirm run_forever() doesn't work in the example calculator_server.py while wait_forever() does... I have absolutely no explanation for this behavior, and it doesn't seem to be an issue on (at least one) other machine(s).

It might be relevant to note that I'm using Gentoo, GCC 8.3.0. I compile capnproto and pycapnp from their respective repos, and I install capnproto locally with `cmake -DCMAKE_INSTALL_PREFIX=/home/cheaterman/.local ..` (from a `cmake` subdir I create in the repo).

**Comment by haata** [comment]
Sorry about that, feel free to open another issue.

Also, I believe in theory the twowaypipe can be used for synchronous code as well. I hadn't created an example of this because it wasn't necessary with the old method available. But it might be tricky to pull off.

To confirm, what you're looking for is that each new object a new socket connection would be opened? On the server side? Client side? Both?

> EDIT2: Definitely a Heisenbug. I recompiled, adding some prints for debugging in both functions, and it seemed like run_forever() became more reliable than wait_forever()... I have absolutely no idea what's going on, possibly something to do with position independent code? I had to add fPIC to capnp's cmakelists... Lemme remove that, and recompile pycapnp without fPIC.

IIRC, -fPIC is required for Python modules (and shared libraries in general).

> Apparently, directly using capnp.wait_forever() does work? I'm not sure why however, because they're functionally equivalent, other than the check on port_promise... I'll keep investigating.

I've been running into something like this as well on Windows. I believe the connection is closed immediately and the timer never returns in all of the async examples. I haven't run into this particular issue on Linux (or macOS) yet. I run both CentOS 6 (old glibc and gcc) as well as Arch Linux (gcc 9.2.1).

How are you compiling capnproto inside of pycapnp?
You may want to force bundling of capnproto and see if that helps at all. I've seen a bunch of issues if capnproto isn't configured correctly.
```pip install --install-option "--force-bundled-libcapnp" .```

**Comment by Cheaterman** [comment]
I usually compile capnproto from upstream git and have pycapnp link against it, however I just tried to force bundled capnp using your command (forgot --user but pip got smart about it as you'll see):
```
cheaterman@cmans-laptop ~ $ cd Dev/pycapnp/                                                                                                                                                                         
cheaterman@cmans-laptop ~/Dev/pycapnp master $ ls                                                                                                                                                                   
CHANGELOG.md  MANIFEST.in  README.md  buildutils  capnp         docs     examples          requirements.txt  setup.cfg  test  tox.ini
LICENSE       Pipfile      benchmark  bundled     cython_debug  example  pycapnp.egg-info  scripts           setup.py   tmp
cheaterman@cmans-laptop ~/Dev/pycapnp master $ pip install --install-option "--force-bundled-libcapnp" .                                                                                                            
Defaulting to user installation because normal site-packages is not writeable
/home/cheaterman/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py:244: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Processing /home/cheaterman/Dev/pycapnp
Skipping wheel build for pycapnp, due to binaries being disabled for it.
Installing collected packages: pycapnp
  Attempting uninstall: pycapnp
    Found existing installation: pycapnp 1.0.0b1
    Uninstalling pycapnp-1.0.0b1:
      Successfully uninstalled pycapnp-1.0.0b1
    Running setup.py install for pycapnp ... done
Successfully installed pycapnp-1.0.0b1
cheaterman@cmans-laptop ~/Dev/pycapnp master $ cd examples/                                                                                                                                                         
cheaterman@cmans-laptop ~/Dev/pycapnp/examples master $ ls                                                                                                                                                          
addressbook.capnp  async_calculator_client.py  async_client.py                   async_server.py      async_ssl_server.py  calculator_client.py  selfsigned.cert  thread.capnp      thread_server.py
addressbook.py     async_calculator_server.py  async_reconnecting_ssl_client.py  async_ssl_client.py  calculator.capnp     calculator_server.py  selfsigned.key   thread_client.py  __pycache__
cheaterman@cmans-laptop ~/Dev/pycapnp/examples master $ python calculator_server.py 127.0.0.1:7890 &                                                                                                                
[1]+ running: python calculator_server.py 127.0.0.1:7890 & & (1990)
cheaterman@cmans-laptop ~/Dev/pycapnp/examples master $ python calculator_client.py 127.0.0.1:7890                                                                                                                  
Traceback (most recent call last):
  File "calculator_client.py", line 306, in <module>
    main(parse_args().host)
  File "calculator_client.py", line 76, in main
    response = read_promise.wait()
  File "capnp/lib/capnp.pyx", line 1935, in capnp.lib.capnp._RemotePromise.wait
capnp.lib.capnp.KjException: capnp/rpc.c++:2092: disconnected: Peer disconnected.
stack: 7f5dd2511ce0 7f5dd25106c0 7f5dd248d68d 7f5dd232f77d 7f5dd23b5f01 7f5dd23b6708 7f5dd23b637e 7f5dd31e1b15 7f5dd31e1c44 7f5dd31c25a0 7f5dd31ba458 7f5dd31c173b 7f5dd3293fe9 7f5dd329425d 7f5dd329428a 7f5dd32bcb83 7f5dd32bf040 7f5dd32bf19b 7f5dd32daabb 7f5dd32dad5d 7f5dd2f81eda 55ee10714099
Evaluating a literal... 
```
I also can reconfirm nothing will work without PIC/PIE :-) so there's that. What puzzles me about this issue is run_forever() isn't doing much more than wait_forever() by itself, so I don't understand why the communication would get closed in one case and not the other... possibly simply accessing the promise attribute for the check tries to resolve it too early? or the delay added by the check allows the promise to silently resolve in the background, and the connection is dropped?

About my merge request, let me just open another issue :-)

Thanks!

**Comment by Cheaterman** [comment]
OK, so I suspect `CYTHON_UNUSED` macro on `self` inside of `run_forever` works around the issue. I suppose this might be caused by some unwanted premature GC. Still investigating.

FWIW I'm using Cython 0.29.15.

**Comment by haata** [comment]
I haven't seen it with gcc 8.2.0 (I use this a bunch at work), but prior versions (all the way to 6.2.0) had a bunch of issues with optimization bugs. So I wouldn't be surprised in this case (it's worth looking at the generated assembly and comparing the two).

Forgive my ignorance, I'm looking for the `CYTHON_UNUSED` macro and can't seem to find any documentation on it.

**Comment by Cheaterman** [comment]
@haata Don't worry, I'm just as ignorant as you are - I merely looked at the generated C++ code and noted this macro is used for the `self` argument of the `run_forever` method whenever I comment the `if` block (or make it `if False` - making the reference to `self` indeed unused), and that's when I saw the `CYTHON_UNUSED` macro appear. I wouldn't bet my hand that this macro fixes the issue, it's more likely they are both (the macro and the fix) a consequence of `self` not being used in the method.

As to why this causes the network to fail... :-/ I still have no idea. I'll investigate more today.

BTW, I think (and certainly hope...) we won't need to dive at the assembly level to understand what's happening here, hopefully reading the generated cpp code and asking the Cython people for some help should be enough! I don't think I'll be able to keep my sanity if I must debug the Python VM at machine code level, hehe.

Thanks for following this @haata, hopefully we can find the problem! Some things I'm going to be attempting today:
- I have GCC 9.2.0 here as well, so I'm going to try compiling with that.
- I'll also try to downgrade Cython to much lower versions, just in case.
- Also, I'll try to find some proper tooling to track Python GC or more generally memory alloc/free, as I still suspect that's what's happening here - I imagine running the examples with and without the hacked `if` block should yield different results, and possibly some intel as to which reference seems to be collected

FWIW, I already investigated (very basically...) the GC and tried to increment the reference counter on the port_promise object, no success. (@haata speaking of which, in `_decref()` in `capnp/lib/capnp.pyx`, you use `Py_INCREF(self._pipe)`, something tells me that's a typo?)

**Comment by Cheaterman** [comment]
Fun fact: it looks like building with GCC 9.2.0 solves the issue:
```
os.environ['CC'] = os.environ['CXX'] = '/usr/bin/g++-9.2.0'
os.environ['LDSHARED'] = os.environ['LDCXXSHARED'] = '/usr/bin/g++-9.2.0 -shared'
```
I simply added these lines to `setup.py` right above the `setup()` call, and it helps.

My testing however highlighted a different issue, that only seems to occur once in a while (I'd say around a third of the time) :
```
cheaterman@cmans-laptop ~/Dev/pycapnp/examples master $ python calculator_client.py 127.0.0.1:7890                                                                                                                  
                fetch_libcapnp(bundle_dir, libcapnp_url)
                fetch_libcapnp(bundle_dir, libcapnp_url)
Evaluating a literal... Traceback (most recent call last):
  File "calculator_client.py", line 306, in <module>
    main(parse_args().host)
  File "calculator_client.py", line 76, in main
    response = read_promise.wait()
  File "capnp/lib/capnp.pyx", line 1935, in capnp.lib.capnp._RemotePromise.wait
capnp.lib.capnp.KjException: (remote):0: disconnected: remote exception: expected nestingLimit > 0; Message is too deeply-nested or contains cycles.  See capnp::ReaderOptions.
stack: 7fb40f23e2a2 7fb40f233f02 7fb40f107fb0 7fb40f103611 7fb40ef8574d 7fb40f019d88 7fb40f01a64a 7fb40f01a233 7fb4100e2b15 7fb4100e2c44 7fb4100c35a0 7fb4100bb458 7fb4100c273b 7fb410194fe9 7fb41019525d 7fb41019528a 7fb4101bdb83 7fb4101c0040 7fb4101c019b 7fb4101dbabb 7fb4101dbd5d 7fb40fe82eda 55b39d665099
```
I also noticed this yesterday, but seeing as a server restart fixes the issue (note that reconnecting the client will not work!) and as this was proof that communication was indeed occurring, it was rather encouraging at that point.

However now that the first issue seems to be solved, this might be something we want to understand and fix. @kentonv sorry to bother you with this, but have you ever seen a similar error?

**Comment by haata** [comment]
I believe this is a sporadic issue with TwoPartyClient and the socket implementation with capnproto (and probably some interference with Python).
I'd suggest using asyncio. I've found that if the server is working it keeps working so it's probably something to do with sockets.
