### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Xiretza** [capnproto/pycapnp#210]
The [documentation linked in the README](http://jparyani.github.io/pycapnp/) is seriously out of date (v0.5.4 from almost 5 years ago). It should either be updated or removed entirely to avoid confusion.

**Comment by haata** [comment]
Agreed! I need to figure out how to regenerate the docs before releasing v1.0.0

**Comment by haata** [comment]
Documentation updated https://capnproto.github.io/pycapnp/
