### ISSUE TITLE
Streams?

### ISSUE THREAD

**Issue by vitaliy-ostapchuk93** [capnproto/pycapnp#215]
Hey guys, great project you have here! I was testing CapnProto for our new API and already finishing up my research with the C++ part. Now, I wanted to test some of the functions in different languages like python and rust and again stuck on the issue to get the streams right. 

`
---------------------------------------------------------------------------
KjException                               Traceback (most recent call last)
<ipython-input-7-63c3eee658e7> in <module>
      1 capnp.add_import_hook()
----> 2 import stream_capnp

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py in _load_backward_compatible(spec)

C:\ProgramData\Anaconda3\lib\site-packages\capnp\lib\capnp.pyx in capnp.lib.capnp._Loader.load_module()

C:\ProgramData\Anaconda3\lib\site-packages\capnp\lib\capnp.pyx in capnp.lib.capnp.load()

C:\ProgramData\Anaconda3\lib\site-packages\capnp\lib\capnp.pyx in capnp.lib.capnp.SchemaParser.load()

KjException: stream.capnp:11: failed: A method declaration uses streaming, but '/capnp/stream.capnp' is not found in the import path. This is a standard file that should always be installed with the Cap'n Proto compiler.
`

Thx to kentonv I know for the c++ part you need to specify the correct include path:
capnp compile "-IC:\Program Files (x86)\Cap'n Proto\include" -oc++ stream.capnp

How does this work in python?

**Comment by haata** [comment]
I haven't tried the new capnproto with pycapnp yet.
It might be as easy as recompiling but there may be some extra code necessary.

**Comment by vitaliy-ostapchuk93** [comment]
Thanks for adding this for the TODO. May I ask if there is any progress or workaround for this?

**Comment by haata** [comment]
I may have some time this week to look at it.

**Comment by haata** [comment]
Sorry about the delay. I've been making some progress.

The main issue is that the .capnp may come from a few places (and that path isn't added to the sys.path).
1. System capnproto (e.g. Arch Linux, macOS brew, etc.)
2. Bundled capnproto (e.g. Pypi, Windows, forced bundle, etc.)

For (1) it should be as simple as adding the system include path (usually /usr/include/capnp; this can be determined at pycapnp compile time if runtime lookup is difficult).
For (2) we'll need to copy .capnp into the python package.

**Comment by haata** [comment]
Also, for future reference it's possible to add lookup paths.

```python
import capnp
add_import_hook(['/usr/include/capnp', '/usr/local/include/capnp'])
```

add_import_hook is called automatically when `import capnp` is done, but it can be called again to use different lookup paths.

If you're bundling capnproto that won't work (as the .capnp files aren't bundled yet). I'll be fixing that as well.

**Comment by haata** [comment]
Should be able to `import stream_capnp` now. I'll be releasing a new beta in a few days.
