### ISSUE TITLE
GitHub Actions Strangeness - Message is too deeply-nested or contains cycles

### ISSUE THREAD

**Issue by haata** [capnproto/pycapnp#222]
This is a strange issue in that it only shows up for macOS on Python 3.7 (not 3.8) and Windows on Python 3.8 (not 3.7). It occasionally shows up for Ubuntu 3.7, but a re-run will usually pass. 

https://github.com/capnproto/pycapnp/runs/770905211?check_suite_focus=true#step:9:102

Basically, when not using asyncio and using libcapnp's socket mechanism (the address and port is passed directly to libcapnp instead of an open file handle). The issue doesn't seem to be tied to capnproto-0.8.0 as capnproto-0.7.0 seems to have a similar issue (though this wasn't a problem when v1.0.0b1 was released).

Since these 3 tests are used to test non-asyncio RPC (all of them fail in each case), I'd rather not waive them

**Comment by haata** [comment]
```
Traceback (most recent call last):
  File "/Users/runner/runners/2.263.0/work/pycapnp/pycapnp/test/../examples/thread_client.py", line 57, in <module>
    main(parse_args().host)
  File "/Users/runner/runners/2.263.0/work/pycapnp/pycapnp/test/../examples/thread_client.py", line 48, in main
    cap.longRunning().wait()
  File "capnp/lib/capnp.pyx", line 1946, in capnp.lib.capnp._RemotePromise.wait
    ret = self._wait()
capnp.lib.capnp.KjException: (remote):0: disconnected: remote exception: expected nestingLimit > 0; Message is too deeply-nested or contains cycles.  See capnp::ReaderOptions.
stack: 100912d40 1008f29c0 1007a2ebf 1007a2d63 1007f8685 10083625f 10008fce2 1001c48cb 1001bc9f5 10008f9ed 1001c481b 1001bd2a3 1001b5e7e 10021866b 100217fd5 100243c59 10024357f 100242b8f 10024284a 10024628e 7fff69dd9cc8
```

**Comment by haata** [comment]
This looks like it's related to something with SO_REUSEADDR. My suspicion is that something in libcapnp isn't handling some tcp spurious packet.

**Comment by kentonv** [comment]
The error indicates that while decoding the message, either a pointer loop was encountered (shouldn't be possible unless the message was corrupted), or the message was more than 64 levels deep (e.g. a struct inside a struct inside a struct inside...).

Hard to see how it could be related to SO_REUSEADDR... any sort of "spurious packets" should be discarded by the OS long before they make it to the application.

**Comment by haata** [comment]
Yeah, I'm not really sure what's going on. It's really only an issue when repeatedly binding and unbinding the socket. I've tried using the c++ calculator client example as well (same problem). Though the c++ calculator server works fine every time (I've been using the code under (capnproto/c++/samples).

Corruption is probably the most likely scenario, unless something is going

When I let Python handle the socket creation it's also ok. So it might have something to do with how the TwoPartyServer is setting up the socket bind.

Python Code (capnp/lib/capnp.pyx)
```python
    cpdef _connect(self, host_string, bootstrap, traversal_limit_in_words, nesting_limit):
        cdef schema_cpp.ReaderOptions opts = make_reader_opts(traversal_limit_in_words, nesting_limit)
        cdef _InterfaceSchema schema
        cdef _EventLoop loop = C_DEFAULT_EVENT_LOOP_GETTER()
        cdef capnp.StringPtr temp_string = capnp.StringPtr(<char*>host_string, len(host_string))
        self._task_set = new capnp.TaskSet(self._error_handler)

        self._bootstrap = bootstrap
        Py_INCREF(self._bootstrap)
        schema = bootstrap.schema
        self.port_promise = _Promise()._init(helpers.connectServer(deref(self._task_set), helpers.server_to_client(schema.thisptr, <PyObject *>bootstrap), loop.thisptr, temp_string, opts))
```

C++ Helper (capnp/helpers/rpcHelper.h)
```c
  kj::Promise<PyObject *> connectServer(kj::TaskSet & tasks, capnp::Capability::Client client, kj::AsyncIoContext * context, kj  ::StringPtr bindAddress, capnp::ReaderOptions & opts) {
      auto paf = kj::newPromiseAndFulfiller<unsigned int>();
      auto portPromise = paf.promise.fork();

      tasks.add(context->provider->getNetwork().parseAddress(bindAddress)
          .then(kj::mvCapture(paf.fulfiller,
            [&, client](kj::Own<kj::PromiseFulfiller<unsigned int>>&& portFulfiller,
                   kj::Own<kj::NetworkAddress>&& addr) mutable {
        auto listener = addr->listen();
        portFulfiller->fulfill(listener->getPort());
        acceptLoop(tasks, client, kj::mv(listener), opts);
      })));

      return portPromise.addBranch().then([&](unsigned int port) { return PyLong_FromUnsignedLong(port); });
  }
```

**Comment by haata** [comment]
I'm going to chock this up to OS oddness when repeatedly using address:port combinations.

Possibly due to an event queue getting stuck (I had something like this happen to me on Rust /w TLS and capnproto where my async await got stuck if a connection was opened but a TLS handshake was never initiated. Ended up having to add a small timeout there in order to service more connections).
I've marked all the example tests that send the address:port string to capnproto directly as xfail so they don't fail unit tests.
When running manually these examples work just fine, it's the automated stuff that dies. The asyncio version works great, likely due to being able to handle the corner cases in Python.

With this I've now run my first 100% successful CI run for pycapnp: https://github.com/capnproto/pycapnp/runs/1429465417?check_suite_focus=true (minus xfails and skips). So I can begin preparing for a v1.0.0.

**Comment by DaneSlattery** [comment]
Just encountered this again when doing something like:

`async def main():
    server = capnp.TwoPartyServer('*:60000', bootstrap=CalculatorImpl())
    await server.poll_forever()
`
I'm noting it here for posterity, but also to note another way to get this error. This happens consistently on Ubuntu in WSL . There is nothing in the docs to suggest this is necessarily botched.

Fixed by not trying to mix sync and async. If using sync, do not use `server.poll_forever()`, instead using `server.run_forever()`.
