### ISSUE TITLE
Fix Read the Docs

### ISSUE THREAD

**Issue by astronouth7303** [capnproto/pycapnp#223]
You have https://capnp.readthedocs.io/ but it seems it hasn't had even an attempted build in years.

**Comment by haata** [comment]
Interesting, didn't know about this one.
I was also trying to setup pycapnp.readthedocs.io. Unfortunately it's rather complicated as readthedocs needs to build pycapnp in order to generate the full docs (due to Cython) and I'm not sure there's an easy way to do this.

**Comment by astronouth7303** [comment]
Looking at https://readthedocs.org/projects/capnp/, it appears that the rtd pages date from before the capnproto org adopted the project.

**Comment by astronouth7303** [comment]
and ooph, i'm not sure I have a clear solution to that. Build environments can be a tricky thing.
