### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by postelrich** [capnproto/pycapnp#227]
I am getting the following error when running `pip install .` with the latest on master on Win10. I ran into this same error when I compiled capnp separately but it didn't inhibit the rest of the build and am able to use pycapnp with that build. I think this error can be ignored and the rest of the install could continue though not sure where to add that logic.

``` 
CMake error : failed to create symbolic link 'C:/Users/myuser/AppData/Local/Temp/pip-req-build-785yalkv/build64/bin/capnpc.exe': operation not permitted [C:\Users\myuser\AppData\Local\Temp\pip-req-build-785yalkv\bundled\capnproto-c++\build64\install.vcxproj]
```

**Comment by haata** [comment]
Which version of Python are you using?

**Comment by haata** [comment]
The latest release has Python 3.7, 3.8 and 3.9 wheels published.
Please use 64-bit Python if possible.

https://pypi.org/project/pycapnp/1.0.0/
