### ISSUE TITLE
Windows Installation failure

### ISSUE THREAD

**Issue by ayush-j9** [capnproto/pycapnp#228]
```
C:\Users\cruser\pycapnp-master\pycapnp-master\bundled\capnproto-c++\src\kj\compat\http.c++(2616,1): fatal error C1001:
Internal compiler error. [C:\Users\cruser\pycapnp-master\pycapnp-master\bundled\capnproto-c++\build32\src\kj\kj-http.vc
xproj]
  (compiler file 'msc1.cpp', line 1591)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\
  bin\HostX64\x86\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
  Building Custom Rule C:/Users/cruser/pycapnp-master/pycapnp-master/bundled/capnproto-c++/src/kj/CMakeLists.txt
  test.c++
```

**Comment by haata** [comment]
How are you trying to install?

What version of Visual Studio do you have?

Is the pypi package not sufficient?

**Comment by ayush-j9** [comment]
I have tried to install it using : pip install pycapnp, python setup.py install and tried using Visual Code but that was not very clear to me.

Visual studio 2019. However, there were build errors with that as well. Internal Compile errors.

The PyPI installation is saying that it cannot find the file: capnp/common.h.

**Comment by kentonv** [comment]
It looks like you're hitting: https://github.com/capnproto/capnproto/issues/1041

This appears to be a regression in Visual Studio. It looks like it has been reported to Microsoft already and they are working on a fix:

https://developercommunity.visualstudio.com/content/problem/1143733/internal-compiler-error-on-v1670.html
https://developercommunity.visualstudio.com/content/problem/1139127/internal-compiler-error-vs-1670.html

As noted in the capnp issue, if someone comes up with a reasonable work-around, we could consider merging it. But, most likely the answer here is to revert to a working version of Visual Studio and wait for Microsoft to fix their bug.

**Comment by haata** [comment]
I haven't had any issues compiling with Visual Studio lately.
Please re-open if the issue persists.
I'll be releasing new python wheels soon which will make this easier as well.
