### ISSUE TITLE
pip fails to build 'capnp.lib.capnp' extension on latest RHEL-based distros

### ISSUE THREAD

**Issue by sarujanai** [capnproto/pycapnp#230]
When I try to install pycapnp on any of RHEL8, CentOS8 or Amazon Linux 2, it first fails to install libcapnp.
If I fetch, build and install libcapnp 0.6.1 myself, it then fails while "building 'capnp.lib.capnp' extension" (see attached verbose pip output) [pip.log](https://github.com/capnproto/pycapnp/files/5140783/pip.log)

I believe this was working just 3 weeks ago so is likely to be caused by either a recent change to pycapnp or an incompatibility with the latest version of one of it's dependencies.
Note: This is working fine on Ubuntu 20.04.

```
    capnp/lib/capnp.cpp: In function ‘PyObject* __pyx_f_5capnp_3lib_5capnp_16_InterfaceSchema_get_dependency(__pyx_obj_5capnp_3lib_5capnp__InterfaceSchema*, PyObject*, int)’:
    capnp/lib/capnp.cpp:66629:62: warning: ‘capnp::Schema capnp::Schema::getDependency(uint64_t) const’ is deprecated [-Wdeprecated-declarations]
         __pyx_t_6 = __pyx_v_self->thisptr.getDependency(__pyx_t_5);
                                                                  ^
    In file included from /usr/local/include/capnp/dynamic.h:40,
                     from ./capnp/helpers/checkCompiler.h:9,
                     from capnp/lib/capnp.cpp:659:
    /usr/local/include/capnp/schema.h:767:15: note: declared here
     inline Schema Schema::getDependency(uint64_t id) const {
                   ^~~~~~
    {standard input}: Assembler messages:
    {standard input}:65313: Warning: end of file not at end of a line; newline inserted
    {standard input}:66664: Error: no such instruction: `mo'
    {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
    gcc: fatal error: Killed signal terminated program cc1plus
    compilation terminated.
    error: command 'gcc' failed with exit status 1
Cleaning up...
  Removing source in /tmp/pip-build-0je2zn8q/pycapnp
```

**Comment by sarujanai** [comment]
It looks like this is only a problem on machines with one processor.
When I beefed up my AWS EC2 instance, it can be installed successfully.
I suspect that this is because of the use of the "-j4" option with make.

Please go ahead and close this issue. 
Although it might be nice to add the minimum CPU/RAM requirements in the "requirements" section on github.

**Comment by haata** [comment]
That's interesting. I don't know if the setup.py build even supports multi core (most of the c++ build is out of one file, so there's not much to parallelize unfortunately).

How much RAM is on your EC2 instance?
