### ISSUE TITLE
`java.capnp` not found

### ISSUE THREAD

**Issue by litghost** [capnproto/pycapnp#231]
I'm working with another team that is using https://github.com/capnproto/capnproto-java to generate capnp output from Java, and they naturally use `java.capnp` in their capnp schema files.  However the current pycapnp installation doesn't include `java.capnp` in the search path, only `c++.capnp` and other capnp files located by https://github.com/capnproto/pycapnp/blob/cb32ddc3209f82abf496742efd2cea29cd16b97a/setup.py#L171

The question is what is the best way to be able to use schema's that use `java.capnp` from `pycapnp`?  As a short term workaround, I copied `java.capnp` to my local python3 site-packages `capnp` path, but that isn't a good long term solution.

I see several potential options:

 1. It appears that the binary tool `capnp` doesn't actually care about missing `java.capnp`, and can process the files anyways, but does generate some errors.  Should `pycapnp` have the ability to gracefully bubble up errors to the user, and give the user to skip import errors like this?
 2. Should `pycapnp` include `java.capnp` from https://github.com/capnproto/capnproto-java/tree/master/compiler/src/main/schema/capnp ?  If so, what is the preferred way of doing this?
 3. Should upstream capnp (e.g. https://github.com/capnproto/capnproto/blob/7e919b98bdf103bd23faf3a861789a0eda8f71de/c%2B%2B/src/capnp/CMakeLists.txt#L60-L63 ) include `java.capnp` in the main capnproto binary distribution?  If this happens, then `pycapnp` will pick up `java.capnp` automatically?

Thoughts?

**Comment by kentonv** [comment]
FWIW the capnp convention is that capnp files intended for reuse should be installed to /usr/include or /usr/local/include, much like C++ headers. I don't actually know if `pycapnp` searches there (I'm not the maintainer of `pycapnp`), but if it doesn't, it probably should.

**Comment by haata** [comment]
@litghost sorry about the delay.

We currently search these paths:
https://github.com/capnproto/pycapnp/blob/5e8ccba536f7bfad08be9bb2ca8e2dd59642b52b/capnp/lib/capnp.pyx#L4130-L4138

If you want to explicitly add more paths you can use the add_import_hook function and then specify additional_paths.

**Comment by kentonv** [comment]
Huh why are `/usr/include/capnp` and `/usr/local/include/capnp` on the list? Those really shouldn't be there. It should only be `/usr/include` and `/usr/local/include`.

**Comment by litghost** [comment]
> FWIW the capnp convention is that capnp files intended for reuse should be installed to /usr/include or /usr/local/include, much like C++ headers. I don't actually know if `pycapnp` searches there (I'm not the maintainer of `pycapnp`), but if it doesn't, it probably should.

It looks like https://github.com/capnproto/capnproto-java doesn't define install targets to `java.capnp` to `/usr/local/include` (or `$PREFIX/include`), nor the binary to `/usr/local/bin` (or `$PREFIX/bin`).  From your comment, it should?

**Comment by haata** [comment]
Those are in there due to the brew (macos) distribution of capnproto.
/usr/local is the standard spot for them.

I can remove it but it'll break brew support.

**Comment by kentonv** [comment]
@haata No no, `/usr/local/include` is fine and correct. The problem is the paths with `/capnp` added to the end. The correct way to import, say, `/capnp/c++.capnp`, is `import "/capnp/c++.capnp"`, but if the search path _includes_ `/capnp` explicitly, then you could import the file as just `/c++.capnp`, which is incorrect.

**Comment by kentonv** [comment]
@litghost I would argue that, yes, capnproto-java should install `java.capnp` to `$PREFIX/include/capnp/java.capnp`. (Or maybe `$PREFIX/include/capnproto-java/java.capnp`... but I think it's OK for capnproto-java to share the `capnp` directory given it's an official member of the capnproto project.)

**Comment by haata** [comment]
> @haata No no, `/usr/local/include` is fine and correct. The problem is the paths with `/capnp` added to the end. The correct way to import, say, `/capnp/c++.capnp`, is `import "/capnp/c++.capnp"`, but if the search path _includes_ `/capnp` explicitly, then you could import the file as just `import "/c++.capnp"`, which is incorrect.

Ah, that makes sense, I'll see how interesting that is to add/fix.
