### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [capnproto/pycapnp#234]
Currently it appears the license file is not included in `sdist`s on PyPI. To ensure users get the license file with these distributions, it would be good to add [the license file to the `setup.cfg`]( https://github.com/pypa/sampleproject/blob/9573ed1c324e736439296d91ed4ad79393934db7/setup.cfg#L1-L4 ). This will ensure that Python packaging tooling will pick up the license file and include it in the distribution.

**Comment by haata** [comment]
Thanks for pointing this out.

**Comment by haata** [comment]
https://github.com/capnproto/pycapnp/commit/528bda300a238ed65d5b68673e29b88d731ac9b7

**Comment by jakirkham** [comment]
Thanks for the fix!
