### ISSUE TITLE
how to save ip of clients in server and if any client is not connected how to remove it from server, using UDP in python

### ISSUE THREAD

**Issue by shehryar51088** [capnproto/pycapnp#236]
I AM USING THIS CODD:

SERVER:
import socket

ip = "127.0.0.1"
localIP = "127.0.0.1"

localPort = 20001

bufferSize = 1024

msgFromServer = "Hello UDP Client"

bytesToSend = str.encode(msgFromServer)

# Create a datagram socket

UDPServerSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)

# Bind to address and ip

UDPServerSocket.bind((localIP, localPort))

print("UDP server up and listening")

# Listen for incoming datagrams

while (True):
    bytesAddressPair = UDPServerSocket.recvfrom(bufferSize)

    message = bytesAddressPair[0]

    address = bytesAddressPair[1]

    clientMsg = "Message from Client:{}".format(message)
    clientIP = "Client IP Address:{}".format(address)

    client = ip
    if localIP == ip:
        print(clientIP)
        print(clientMsg)
    else:
        print("ip not correct")

    # Sending a reply to client

    UDPServerSocket.sendto(bytesToSend, address)

CLIENT:
import socket
import time

count = 0
while count < 5:

    msgFromClient = "Hello"
    bytesToSend = str.encode(msgFromClient)

    serverAddressPort = ("127.0.0.1", 20001)

    bufferSize = 1024

# Create a UDP socket at client side

    UDPClientSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)

# Send to server using created UDP socket

    UDPClientSocket.sendto(bytesToSend, serverAddressPort)

    msgFromServer = UDPClientSocket.recvfrom(bufferSize)

    msg = "Message from Server {}".format(msgFromServer[0])

    print(msg)
    time.sleep(3)

**Comment by haata** [comment]
Is this a question?

**Comment by shehryar51088** [comment]
@haata YES THIS IS QUESTION,PLEASE HELP

**Comment by haata** [comment]
I don't think this is the appropriate place to ask general python questions.
Please inquire somewhere like https://stackoverflow.com/.
This is the bug tracker for pycapnp.
