### ISSUE TITLE
Build does not track code quality

### ISSUE THREAD

**Issue by thedrow** [capnproto/pycapnp#43]
Can you please activate landscape.io so that code quality can be tracked over time?

**Comment by jparyani** [comment]
I believe this would have the same problem as coveralls.io from issue #42, but I'm actually not sure. I'm also more ok with enabling this, as it's much less misleading than claiming 100% coverage.

I'll try it out and see how it looks.

**Comment by jayvdb** [comment]
CI now runs flake8, and https://github.com/capnproto/pycapnp/pull/255 increases the number of active rules and also applies them to the Cython code.

https://landscape.io is dead.  Long live GitHub Actions, and the Microsoft overlords.

IMO this can be closed, with https://github.com/capnproto/pycapnp/issues/128 tracking increasing the use of code quality checks, and other quality improvements.
