### ISSUE TITLE
install on windows

### ISSUE THREAD

**Issue by narsu1984** [capnproto/pycapnp#53]
I wanna use pycapnp on windows.I followed the instructions on your website to install C++ Cap’n Proto Library first, but there are no leads for windows users. I downloaded capnproto-c++-win32-0.5.1 from https://capnproto.org/capnproto-c++-win32-0.5.1.zip but still i don't know how to install it on windows.Would you help out ?

**Comment by jparyani** [comment]
Unfortunately, C++ Cap'n Proto for Windows can only be built with the CAPNP_LITE option enabled (see https://capnproto.org/install.html). This disables the dynamic API which is required to build pycapnp. As soon as support is added for building the dynamic API under windows, I'll try to get it working with pycapnp.

**Comment by narsu1984** [comment]
Thanks for your prompt reply. I'm looking forward to its compatibility with windows. Thanks again and have a great day!

**Comment by rcrowder** [comment]
Could this issue be left open until resolved? Or are you saying that a CAPNP_LITE version will work with Pycapnp, hence the closure.

**Comment by jparyani** [comment]
I'll re-open the issue.

Also, I learned recently that the mingw port of C++ Cap'n Proto _does_ have the dynamic API, so technically that could work. If I remember correctly, Python and all its modules must be compiled with mingw if you want to go down this route. Unfortunately, I don't have a windows box around to test this.

**Comment by rcrowder** [comment]
Thanks for re-opening. Mingw is my next stop in hopefully creating a 64 bit wheel for AppVeyor CI.

**Comment by sbant** [comment]
I'm also interest in windows version

I've install WinPython( https://winpython.github.io/ ) 3.4.3.1, and some of the other library I use can't build with msvc2010, but successful built with MinGW-W64 bundled within the WinPython, and the libary works well

so I think “ Python and all its modules must be compiled with mingw if you want to go down this route”
is not a problem...

**Comment by sbant** [comment]
add..

in WinPython 3.4.3.1, the python.exe was built with [MSC v.1600 64 bit (AMD64)] (MS VC++ 10.0, VS2010)

**Comment by jparyani** [comment]
I was mostly going off information like this (https://github.com/cython/cython/wiki/64BitCythonExtensionsOnWindows#less-useful-information). According to the cython developers, using multiple different C++ runtimes in Python can lead to subtle and annoying runtime errors.

**Comment by sbant** [comment]
after more search, I found this, just copy from the web

http://nbviewer.ipython.org/github/winpython/winpython_afterdoc/blob/master/examples/using_cython_and_numba_under_winpython.ipynb
in October 2014 WinPython added "MinGW-Compiler and fully integrated Cython and Numba"
what the most important is "mingw-w64 'static' version"

as if runtime is static linked, then there is no mix runtimes


btw, I tried to build pycapnp on windows, the build command lines always use the msvc2010, I haven't got a chance to set it to mingw-w64

**Comment by jparyani** [comment]
That's cool, but I'm not sure it proves my concern wrong. Numba is compiling to C, whereas we have to deal with C++ runtimes. My major concern is C++ exceptions not mixing well.

That being said, this discussion is moot until we get pycapnp building with mingw. Once that's happening, we can revisit this, and figure out if it's safe to distribute wheels that will work with msvc pythons.

**Comment by sbant** [comment]
I'm not be familiar with the setup.py scripts, so I hard coded like below, and successful set the compiler to mingw
file: buildutils/detect.py, line 155
detected = detect_version(tmp_dir)  ->  detected = detect_version(tmp_dir,compiler='mingw32')

C:\Users\sbant\AppData\Local\Temp\tmp36cvyctv\vers.cpp:4:26: fatal error: capnp/
common.h: No such file or directory
 #include "capnp/common.h"
                          ^
compilation terminated.
*WARNING* no libcapnp detected. Will download and build it from source now. If y
ou have C++ Cap'n Proto installed, it may be out of date or is not being detecte
d. Downloading and building libcapnp may take a while.
already have bundled\capnproto-c++
error: [WinError 2] Cannot find the file

the setup.py downloaded the capnproto-c++-0.5.1.1.tar.gz and extracted to capnproto-c++
then stopped

**Comment by sbant** [comment]
after several hours... I finally built Cap’n Proto(not pycapnp) use the MinGW-W64 bundled within the WinPython.

I use CMake 3.2.0, and unchecked BUILD_TESTING
these files ok：
libcapnpc.a, libcapnp-rpc.a, libcapnp.a, libkj.a
this file failed
libkj-async.a (async-unix.c++ can not fild <pool.h>)

I also find pycapnp maybe not contain windows build scripts,
setup.py line 109: build_libcapnp(bundle_dir, build_dir)
then build.py def build_libcapnp(bundle_dir, build_dir, verbose=False):

the build_libcapnp looks like can only use in linux

**Comment by jparyani** [comment]
Oh ya you're definitely going to want to skip the build_capnp step. You can pass the "--force-system-libcapnp" flag to setup.py, but it won't really help you since that error is occurring because of the capnp headers not being found. You'll have to make sure that the headers are in your include path, and libraries are in your library path. I'm not sure how best to do this on windows, but it may require you to edit setup.py and add them explicitly to the Extension or cythonize functions.

libkj-async is required for pycapnp. It seems that this library may not build at all on mingw (see https://capnproto.org/install.html#supported-operating-systems). We could maybe refactor the serialization bits to not depend on it, and then only build the serialization layer for windows, but it would be a fair bit of work.

**Comment by sbant** [comment]
small progress...

setup.py line 125:
include_dirs=["."],   ->   include_dirs=['bundled/capnproto-c++/src'],

buildutils/detect.py line 126: add these
    compiler_attrs['include_dirs'] = []
    compiler_attrs['include_dirs'].append('bundled/capnproto-c++/src')
(the function just check platform if it's linux, but don't do any on other platform)

the real problem is whether set --force-system-libcapnp, the build always run the cythonize

and there are may errors when cython the capnp/lib/capnp.pyx
Signature not compatible with previous declaration

maybe that's the problem?

**Comment by jparyani** [comment]
Oh that's a known problem when using Cython v0.22. It will be fixed whenever v0.22.1 is released, but for now just do `pip install cython==0.21.2`

**Comment by sbant** [comment]
after installed cython v0.21.2, I finally able to built all then hit the link error wall ...  -o- 
stop now until Cap'n Proto resolved this, I've post an issue on Cap'n Proto's repo, there is no reply now

summary: (below maybe contains dirty code... just for reference)
environment: WinPython 3.4 x64, use built-in MinGW-W64(gcc-4.9.2)

changes:
buildutils/detect.py, line 155
detected = detect_version(tmp_dir) -> detected = detect_version(tmp_dir,compiler='mingw32')
buildutils/detect.py, line 126: add these
compiler_attrs['include_dirs'] = []
compiler_attrs['include_dirs'].append('bundled/capnproto-c++/src')
setup.py, line 125:
include_dirs=["."], -> include_dirs=['.', 'bundled/capnproto-c++/src'] (then, base_dir and bundled/capnproto-c++/src both contain the "capnp" dir, is that ok?)

in my environment(don't know how to change the include and libary path), also need to copy "capnp" and "kj" dir under "src" to python_dir/include,
copy the built lib(libcapnpc.a, libcapnp-rpc.a, libcapnp.a, libkj.a libkj-async.a) to python_dir/libs and rename these files to .lib (libcapnpc.a -> capnpc.lib)

**Comment by rubber-duck** [comment]
I don't have a windows machine to try this out right now but I'm might need to port some pycapnp code to Windows soon so I'm interested if anyone made any progress on this. 

Did someone try to use [clang-cl driver](http://clang.llvm.org/docs/UsersManual.html#clang-cl) to build capnp and pycapnp ?  This would (presumably) link the same run-time as MSVC and let you run code on standard python builds ?

**Comment by haata** [comment]
As an FYI, after quite a bit of work I have a mostly working version of pycapnp on Windows.
https://github.com/haata/pycapnp-async

I need to fix a getTimer() bug when doing asyncio servers, but I think that's the last piece. General client RPC seems to be working fine.

**Comment by haata** [comment]
Now upstreamed to `master`. Will push to Pypi after a few more issues are ironed out.
