### ISSUE TITLE
`test_roundtrip_dict` failure with TravisCI + PyPy

### ISSUE THREAD

**Issue by jparyani** [capnproto/pycapnp#58]
TravisCI's PyPy is failing `test_roundtrip_dict` for some reason (https://travis-ci.org/jparyani/pycapnp/builds/53250904), and it's not reproducible on my local PyPy. I'm going to skip the test for now, but leave this issue open until I've verified it's fixed.

**Comment by breznak** [comment]
I think nupic is not able to run under pypy anyway.

**Comment by haata** [comment]
This is working with GitHub Actions (Windows, Linux, macOS).
