### ISSUE TITLE
Upload prebuilt binary wheels for Windows and Mac on PyPI

### ISSUE THREAD

**Issue by dahlia** [capnproto/pycapnp#60]
Currently pycapnp package officially provides only a source distribution.  Source distributions are easy enough to install using `pip`, but become picky when it comes to C extensions, on Windows in particular.  Moreover recent versions of Xcode on Mac cannot build extensions written in C++11 without preconfigured `CFLAGS`/`CXXFLAGS` environment variables.

In case of libsass-python, which also uses C++11 and has been maintained by myself, [it provides prebuilt binary wheels](https://pypi.python.org/pypi/libsass#downloads) for `win32`/`win_amd64`/`macosx` as well as source distribution.

Yes, yes, I know, it’s sort of very troublesome work.  One good news is some part of the work could be automated using free CI services: Travis CI and [AppVeyor](http://www.appveyor.com/).  Travis CI provides Mac platform as well as Linux, and AppVeyor is a hosted CI service specialized for Windows platform.

If you’re interested in this, take a look at [libsass-python’s automated Windows build](https://github.com/dahlia/libsass-python/blob/python/appveyor.yml).  :smile:

Thanks for reading this!
Minhee

**Comment by jparyani** [comment]
Hey Minhee,

Thanks, but I'm a little bit concerned about the portability of these wheels. Considering the fact that we compile the full Cap'n Proto C++ distribution and statically link it in, does that cause any problems? What if libc or stdlibc++ has version mismatches? Also, on OSX, how well are different Python distributions handled (ie. homebrew vs macports vs system default).

Thanks,
Jason

**Comment by dahlia** [comment]
AFAIK wheels don’t match if it’s built using different Python distribution.  For example, libsass-python’s Mac binary wheels are rejected by pip if Python is installed using Homebrew, since the wheels are built using official Python installer (distributed by python.org), and pip chooses source distributions instead.

I believe it could be thought of a small optimization of package installation.  If it does not work well, source distributions are used instead.

**Comment by haata** [comment]
I will be handling this for the upcoming v1.0.0 release.

**Comment by haata** [comment]
Now available starting from v1.0.0b1

https://pypi.org/project/pycapnp/1.0.0b1/#files
